# Generated by Django 2.2 on 2020-04-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_testapp', '0004_remove_trip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ManyToManyField(related_name='trips', to='belt_testapp.User'),
        ),
    ]
