# Generated by Django 2.2 on 2020-04-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_testapp', '0005_trip_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
                ('description', models.TextField(max_length=1000)),
                ('category', models.TextField(max_length=45)),
                ('user', models.ManyToManyField(related_name='jobs', to='belt_testapp.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
